export const queryKeys = {
	users: 'users',
	workspaces: 'workspaces',
	forms: 'forms',
	singleForm: 'singleForm',
	formResponses: 'formResponses',
	projects: 'projects',
	formAnalytics: 'formAnalytics',
	workspaceInvites: 'workspaceInvites',
	permissions: 'permissions',
	roles: 'roles',
	barePermissions: 'barePermissions',
	userActivity: 'userActivity',
	workspaceActivity: 'workspaceActivity',
} as const;
