// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID
	Deleted      *bool
	CreatedAt    pgtype.Timestamptz
	Name         string
	Email        string
	Phone        string
	Avatar       string
	Deactivated  *bool
	Provider     string
	Password     string
	RefreshToken string
}

type UserInvite struct {
	ID                uuid.UUID
	Deleted           *bool
	CreatedAt         pgtype.Timestamptz
	WorkspaceID       uuid.UUID
	Name              string
	Email             string
	Status            *int64
	PlainTextPassword *string
}

type UsersWorkspacesRelation struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

type Workspace struct {
	ID          uuid.UUID
	Name        *string
	Description *string
	Deleted     *bool
	CreatedAt   pgtype.Timestamptz
	CreatedByID uuid.UUID
}
