// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: permission.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addBarePermissionToUser = `-- name: AddBarePermissionToUser :exec
insert into bare_permissions (
	id,
	user_id,
	workspace_id,
	object_type,
	object_id,
	level
) values ($1, $2, $3, $4, $5, $6)
`

type AddBarePermissionToUserParams struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"user_id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	ObjectType  ObjectType      `json:"object_type"`
	ObjectID    uuid.UUID       `json:"object_id"`
	Level       PermissionLevel `json:"level"`
}

func (q *Queries) AddBarePermissionToUser(ctx context.Context, arg AddBarePermissionToUserParams) error {
	_, err := q.db.Exec(ctx, addBarePermissionToUser,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.ObjectType,
		arg.ObjectID,
		arg.Level,
	)
	return err
}

const getUserBarePermissions = `-- name: GetUserBarePermissions :many
select id, object_type, object_id, user_id, workspace_id, level from bare_permissions where user_id = $1 and workspace_id = $2
`

type GetUserBarePermissionsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetUserBarePermissions(ctx context.Context, arg GetUserBarePermissionsParams) ([]BarePermission, error) {
	rows, err := q.db.Query(ctx, getUserBarePermissions, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BarePermission
	for rows.Next() {
		var i BarePermission
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.ObjectID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBarePermissionFromUser = `-- name: RemoveBarePermissionFromUser :exec
delete from bare_permissions where user_id = $1 and workspace_id = $2 and level = $3 and object_type = $4 and object_id = $5
`

type RemoveBarePermissionFromUserParams struct {
	UserID      uuid.UUID       `json:"user_id"`
	WorkspaceID uuid.UUID       `json:"workspace_id"`
	Level       PermissionLevel `json:"level"`
	ObjectType  ObjectType      `json:"object_type"`
	ObjectID    uuid.UUID       `json:"object_id"`
}

func (q *Queries) RemoveBarePermissionFromUser(ctx context.Context, arg RemoveBarePermissionFromUserParams) error {
	_, err := q.db.Exec(ctx, removeBarePermissionFromUser,
		arg.UserID,
		arg.WorkspaceID,
		arg.Level,
		arg.ObjectType,
		arg.ObjectID,
	)
	return err
}
