/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppsFormsIndexImport } from './routes/apps/forms/index'
import { Route as AppsFormsDesignerImport } from './routes/apps/forms/designer'
import { Route as AppsFormsBuilderImport } from './routes/apps/forms/builder'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppsFormsIndexRoute = AppsFormsIndexImport.update({
  path: '/apps/forms/',
  getParentRoute: () => rootRoute,
} as any)

const AppsFormsDesignerRoute = AppsFormsDesignerImport.update({
  path: '/apps/forms/designer',
  getParentRoute: () => rootRoute,
} as any)

const AppsFormsBuilderRoute = AppsFormsBuilderImport.update({
  path: '/apps/forms/builder',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/apps/forms/builder': {
      preLoaderRoute: typeof AppsFormsBuilderImport
      parentRoute: typeof rootRoute
    }
    '/apps/forms/designer': {
      preLoaderRoute: typeof AppsFormsDesignerImport
      parentRoute: typeof rootRoute
    }
    '/apps/forms/': {
      preLoaderRoute: typeof AppsFormsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  AuthLoginRoute,
  AppsFormsBuilderRoute,
  AppsFormsDesignerRoute,
  AppsFormsIndexRoute,
])

/* prettier-ignore-end */
